<?php

return [
    [
        'key'  => 'sales.abandoned_cart',
        'name' => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.title',
        'info' => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.info',
        'sort' => 99,
    ],

    [
        'key'    => 'sales.abandoned_cart.general',
        'name'   => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.title',
        'info'   => '',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'enabled',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.enabled',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => true,
            ],
            [
                'name'          => 'inactivity_threshold_minutes',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.inactivity-threshold',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 60,
            ],
            [
                'name'          => 'max_notification_attempts',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.max-attempts',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 3,
            ],
            [
                'name'          => 'attempt_1_delay_hours',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.attempt-1-delay',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 1,
            ],
            [
                'name'          => 'attempt_2_delay_hours',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.attempt-2-delay',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 24,
            ],
            [
                'name'          => 'attempt_3_delay_hours',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.attempt-3-delay',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 72,
            ],
            [
                'name'          => 'auto_cancel_after_max_attempts',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.auto-cancel',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => false,
            ],
            [
                'name'          => 'require_admin_approval_to_cancel',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.general.require-approval',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => true,
            ],
        ],
    ],

    [
        'key'    => 'sales.abandoned_cart.channels',
        'name'   => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.title',
        'info'   => '',
        'sort'   => 2,
        'fields' => [
            [
                'name'          => 'email_enabled',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.email-enabled',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => true,
            ],
            [
                'name'          => 'whatsapp_enabled',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.whatsapp-enabled',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => false,
            ],
            [
                'name'          => 'whatsapp_api_token',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.whatsapp-token',
                'type'          => 'password',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'whatsapp_from_number',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.whatsapp-phone-id',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'messenger_enabled',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.messenger-enabled',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => false,
            ],
            [
                'name'          => 'messenger_page_access_token',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.messenger-token',
                'type'          => 'password',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'messenger_page_id',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.channels.messenger-page-id',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
            ],
        ],
    ],

    [
        'key'    => 'sales.abandoned_cart.fraud',
        'name'   => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.fraud.title',
        'info'   => '',
        'sort'   => 3,
        'fields' => [
            [
                'name'          => 'fraud_detection_enabled',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.fraud.enabled',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => true,
            ],
            [
                'name'          => 'auto_flag_score_threshold',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.fraud.threshold',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 60,
            ],
            [
                'name'          => 'block_disposable_emails',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.fraud.block-disposable',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => true,
            ],
            [
                'name'          => 'velocity_check_window_minutes',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.fraud.velocity-window',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 60,
            ],
            [
                'name'          => 'velocity_check_max_orders',
                'title'         => 'abandoned-cart::app.configuration.index.sales.abandoned-cart.fraud.velocity-max',
                'type'          => 'text',
                'channel_based' => true,
                'locale_based'  => false,
                'default'       => 5,
            ],
        ],
    ],
];
